# -*- coding: utf-8 -*-
"""Mineracao2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16GWd0HFOzL4fycaH7tuuq-XmdceXXEMZ

Mineração de Dados

Nome: Caio Passos de Lima Albuquerque 536506
"""

# Criar dataset de vendas
np.random.seed(42)
vendas_df = pd.DataFrame({
    'mes': ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun',
            'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'] * 3,
    'categoria': ['Eletrônicos']*12 + ['Roupas']*12 + ['Alimentos']*12,
    'vendas': np.random.randint(5000, 20000, 36),
    'lucro': np.random.randint(500, 5000, 36)
})

print("Dataset de Vendas:")
print(vendas_df.head(15))
print(f"\nShape: {vendas_df.shape}")

"""#### Tarefa 1a: Gráfico de linhas - Vendas mensais por categoria"""

# TODO: Crie um gráfico de linhas mostrando as vendas mensais de cada categoria
# Dica: use um loop for para plotar cada categoria com uma cor diferente

# Sua solução aqui:
plt.figure(figsize = (12,6))
categorias = vendas_df['categoria'].unique()
cores = ['steelblue','coral', 'limegreen']

for i,cat in enumerate(categorias):
    data_cat = vendas_df[vendas_df['categoria'] == cat]
    plt.plot(data_cat['mes'], data_cat['vendas'], label=cat, color=cores[i], marker = 'o', linewidth = 2)

plt.title('Vendas Mensais por Categoria')
plt.xlabel('Mês')
plt.ylabel('Vendas (R$)')
plt.legend()
plt.grid(True, alpha = 0.3, linestyle='--')
plt.tight_layout()
plt.show()

"""#### Tarefa 1b: Gráfico de barras empilhadas"""

# TODO: Crie um gráfico de barras empilhadas com vendas totais por categoria
# Dica: use pivot_table do pandas e o método .plot(kind='bar', stacked=True)

# Sua solução aqui:
tabela_empilhada = vendas_df.pivot_table(index='mes', columns='categoria', values='vendas', aggfunc='sum')

tabela_empilhada.plot(kind='bar', stacked=True, figsize=(12, 6),colormap = 'tab10')
plt.title('Vendas mensair por categoria')
plt.xlabel('Mês')
plt.ylabel('Vendas (R$)')
plt.legend(title ='Categoria')
plt.tight_layout()
plt.show()

"""#### Tarefa 1c: Scatter plot - Vendas vs Lucro"""

# TODO: Crie um scatter plot relacionando vendas e lucro, colorido por categoria
# Dica: use um loop ou seaborn.scatterplot com hue='categoria'

# Sua solução aqui:
plt.figure(figsize = (10,7))
sns.scatterplot(data = vendas_df, x = 'vendas', y = 'lucro', hue = 'categoria', palette = 'Set2')
plt.title('Vendas vs Lucro por Categoria')
plt.xlabel('Vendas (R$)')
plt.ylabel('Lucro (R$)')
plt.grid(True, alpha = 0.3)
plt.tight_layout()
plt.show()

"""#### Tarefa 1d: Heatmap de correlação"""

# TODO: Calcule e visualize a correlação entre vendas e lucro
# Dica: use .corr() e sns.heatmap()

# Sua solução aqui:
corr = vendas_df[['vendas','lucro']].corr()

plt.figure(figsize = (8,6))
sns.heatmap(corr, annot = True, cmap = 'RdYlGn', center = 0,fmt =".2f", linewidths=1, square = True)
plt.title('Correlação entre Vendas e Lucro')
plt.tight_layout()
plt.show()

"""### Exercício 2: Análise de Clientes

**Objetivo:** Analisar perfil de clientes de uma empresa.
"""

# Criar dataset de clientes
np.random.seed(123)
n_clientes = 500

clientes_df = pd.DataFrame({
    'idade': np.random.randint(18, 70, n_clientes),
    'renda': np.random.normal(5000, 2000, n_clientes),
    'gastos': np.random.normal(1500, 800, n_clientes),
    'tempo_cliente': np.random.randint(1, 120, n_clientes),
    'satisfacao': np.random.randint(1, 11, n_clientes),
    'categoria': np.random.choice(['Bronze', 'Prata', 'Ouro'], n_clientes)
})

# Adicionar correlações
clientes_df['gastos'] = 0.3 * clientes_df['renda'] + np.random.normal(0, 500, n_clientes)
clientes_df['satisfacao'] = (5 + 0.03 * clientes_df['tempo_cliente'] +
                             np.random.normal(0, 2, n_clientes)).clip(1, 10)

print("Dataset de Clientes:")
print(clientes_df.head())
print(f"\nShape: {clientes_df.shape}")

"""#### Tarefa 2a: Histogramas múltiplos"""

# TODO: Crie 3 subplots (1 linha, 3 colunas) com histogramas de:
# - Idade
# - Renda
# - Gastos

# Sua solução aqui:
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# Histograma da Idade
axes[0].hist(clientes_df['idade'], bins=20, color='skyblue', edgecolor='black')
axes[0].set_title('Histograma da Idade')
axes[0].set_xlabel('Idade')
axes[0].set_ylabel('Frequência')

# Histograma da Renda
axes[1].hist(clientes_df['renda'], bins=20, color='salmon', edgecolor='black')
axes[1].set_title('Histograma da Renda')
axes[1].set_xlabel('Renda')
axes[1].set_ylabel('Frequência')

# Histograma dos Gastos
axes[2].hist(clientes_df['gastos'], bins=20, color='lightgreen', edgecolor='black')
axes[2].set_title('Histograma dos Gastos')
axes[2].set_xlabel('Gastos')
axes[2].set_ylabel('Frequência')

plt.tight_layout()
plt.show()

"""#### Tarefa 2b: Boxplot comparativo"""

# TODO: Crie um boxplot comparando gastos por categoria de cliente

# Sua solução aqui:
plt.figure(figsize=(10, 6))
sns.boxplot(x='categoria', y='gastos', data=clientes_df, palette='Pastel1')
plt.title('Comparação dos Gastos por Categoria de Cliente')
plt.xlabel('Categoria')
plt.ylabel('Gastos')
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

"""#### Tarefa 2c: Scatter plot avançado"""

# TODO: Crie um scatter plot de renda vs gastos
# Colorido por categoria e com tamanho dos pontos proporcional à satisfação

# Sua solução aqui:
plt.figure(figsize=(10, 7))
sns.scatterplot(data=clientes_df, x='renda', y='gastos', hue='categoria',
size='satisfacao', sizes=(20, 200), palette='Set2', alpha=0.7, edgecolor='gray')
plt.title('Renda vs Gastos por Categoria com Tamanho por Satisfação')
plt.xlabel('Renda')
plt.ylabel('Gastos')
plt.legend(title='Categoria', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

"""#### Tarefa 2d: Gráfico de violino"""

# TODO: Crie um gráfico de violino mostrando a distribuição de satisfação
# por categoria de cliente

# Sua solução aqui:
plt.figure(figsize=(10, 6))
sns.violinplot(x='categoria', y='satisfacao', data=clientes_df, palette='Pastel2')
plt.title('Distribuição da Satisfação por Categoria de Cliente')
plt.xlabel('Categoria')
plt.ylabel('Satisfação')
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

"""### Exercício 3: Dashboard do Titanic

**Objetivo:** Criar um dashboard completo de análise do dataset Titanic.
"""

# Carregar dataset Titanic
titanic = sns.load_dataset('titanic')

print("Dataset Titanic:")
print(titanic.head())
print(f"\nShape: {titanic.shape}")
print(f"\nTaxa geral de sobrevivência: {titanic['survived'].mean():.2%}")

"""#### Tarefa 3: Criar dashboard com 6 visualizações"""

# TODO: Crie uma figura com 6 subplots (2 linhas, 3 colunas) mostrando:
# 1. Taxa de sobrevivência por classe (gráfico de barras)
# 2. Distribuição de idade (histograma)
# 3. Sobrevivência por sexo (gráfico de barras)
# 4. Idade vs Tarifa, colorido por sobrevivência (scatter)
# 5. Boxplot de tarifa por classe
# 6. Heatmap de correlação entre variáveis numéricas

# Sua solução aqui:
fig, axes = plt.subplots(2, 3, figsize=(18, 12),squeeze = False)

sns.barplot(x='class', y='survived', data=titanic, ax=axes[0, 0], ci=None, palette='muted')
axes[0, 0].set_title('Taxa de Sobrevivência por Classe')
axes[0, 0].set_ylabel('Taxa de Sobrevivência')
axes[0, 0].set_xlabel('Classe')


titanic['age'].plot.hist(bins=30, ax=axes[0, 1], color='skyblue', edgecolor='black')
axes[0, 1].set_title('Distribuição de Idade')
axes[0, 1].set_xlabel('Idade')
axes[0, 1].set_ylabel('Frequência')

sns.barplot(x='sex', y='survived', data=titanic, ax=axes[0, 2], ci=None, palette='pastel')
axes[0, 2].set_title('Taxa de Sobrevivência por Sexo')
axes[0, 2].set_ylabel('Taxa de Sobrevivência')
axes[0, 2].set_xlabel('Sexo')

sns.scatterplot(x='age', y='fare', hue='survived', data=titanic, ax=axes[1, 0], palette='coolwarm', alpha=0.7)
axes[1, 0].set_title('Idade vs Tarifa por Sobrevivência')
axes[1, 0].set_xlabel('Idade')
axes[1, 0].set_ylabel('Tarifa')


sns.boxplot(x='class', y='fare', data=titanic, ax=axes[1, 1], palette='Set3')
axes[1, 1].set_title('Boxplot da Tarifa por Classe')
axes[1, 1].set_xlabel('Classe')
axes[1, 1].set_ylabel('Tarifa')

sns.heatmap(corr, annot=True, cmap='RdYlBu_r', center=0, ax=axes[1, 2])
axes[1, 2].set_title('Matriz de Correlação')

plt.tight_layout()
plt.show()

"""### Exercício 4: Séries Temporais

**Objetivo:** Analisar e visualizar dados de séries temporais.
"""

# Criar dados de série temporal
np.random.seed(42)
datas = pd.date_range('2020-01-01', periods=365*3, freq='D')
trend = np.linspace(100, 150, len(datas))
seasonal = 10 * np.sin(np.arange(len(datas)) * 2 * np.pi / 365)
noise = np.random.normal(0, 5, len(datas))
valores = trend + seasonal + noise

series_df = pd.DataFrame({
    'data': datas,
    'valor': valores
})
series_df['mes'] = series_df['data'].dt.to_period('M')
series_df['ano'] = series_df['data'].dt.year

print("Série Temporal:")
print(series_df.head())

"""#### Tarefa 4a: Gráfico da série completa com média móvel"""

# TODO: Plote a série temporal completa
# Adicione uma média móvel de 30 dias

# Sua solução aqui:
plt.figure(figsize=(14, 6))
plt.plot(series_df['data'], series_df['valor'], label='Valor', color='steelblue', alpha=0.7)
series_df['media_movel_30'] = series_df['valor'].rolling(window=30).mean()
plt.plot(series_df['data'], series_df['media_movel_30'], label='Média Móvel 30 dias', color='red', linewidth=2)

plt.title('Série Temporal com Média Móvel de 30 dias')
plt.xlabel('Data')
plt.ylabel('Valor')
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

"""#### Tarefa 4b: Subplots por ano"""

# TODO: Crie 3 subplots (um para cada ano)

# Sua solução aqui:
anos = series_df['ano'].unique()
fig, axes = plt.subplots(3, 1, figsize=(14, 12), sharex=True)

for i, ano in enumerate(anos):
    df_ano = series_df[series_df['ano'] == ano]
    axes[i].plot(df_ano['data'], df_ano['valor'], label='Valor diário', color='steelblue', alpha=0.7)
    media_movel_ano = df_ano['valor'].rolling(window=30).mean()
    axes[i].plot(df_ano['data'], media_movel_ano, label='Média móvel 30 dias', color='red', linewidth=2)
    axes[i].set_title(f'Série Temporal para o ano {ano}')
    axes[i].set_ylabel('Valor')
    axes[i].legend()
    axes[i].grid(alpha=0.3)

axes[-1].set_xlabel('Data')
plt.tight_layout()
plt.show()

"""### Exercício 5 (Desafio): Visualização Interativa com Plotly"""

# Instalar plotly se necessário
# !pip install plotly

import plotly.express as px
import plotly.graph_objects as go

# TODO: Crie um gráfico de bolhas animado com o dataset gapminder
# mostrando PIB per capita vs expectativa de vida ao longo dos anos

# Sua solução aqui:
import plotly.express as px
import plotly.io as pio

gapminder = px.data.gapminder()
fig = px.scatter(gapminder, x='gdpPercap', y='lifeExp',
  animation_frame='year', animation_group='country',
  size='pop', color='continent', hover_name='country', log_x=True, size_max=60,
  labels={'gdpPercap': 'PIB per Capita', 'lifeExp': 'Expectativa de Vida'},
  title='PIB per Capita vs Expectativa de Vida ao Longo dos Anos')

fig.update_layout(transition={'duration': 500})
pio.show(fig)